### ISSUE TITLE
software filters should try to filter hi-res frames too

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#104]
I have noticed on bsnes-mcfly which is using bsnes as its emulator core filters such as 2xsai are able to be applied to hires games such as ASP.

Can whatever trick is used in that emulator be done here?

**Comment by Screwtapello** [comment]
Air Strike Patrol is not a hi-res game. A good example of hi-res would be the first menu of Seiken Densetsu 3, and I think the Interplay logo at the beginning of R.P.M. Racing is both hi-res and interlaced.

**Comment by jjfmz42015** [comment]
Oh so maybe the filters don't happen on dot ppu. But they do in McFly using bsnes core so the possibility does exist. Don't know if  
@hexuser can share why

**Comment by Screwtapello** [comment]
Looking at https://gitlab.com/hex-usr/bsnes-mcfly/blob/master/filters/HQ2x/HQ2x.cpp (and other filters), it seems to work like this:

- if the input texture is <= 256px wide, filtering occurs as normal
- if the input texture is >256px, and two adjacent pixels are identical, it filters the first pixel and ignores the other (effectively down-sampling back to low-res)
- if the input texture is >256px, and two adjacent pixels are different, it uses them as-is instead of running them through the filter algorithm

That actually seems pretty reasonable, and should even work on images that are part-hi-res and part-low-res like certain RPGs when a text-box appears. Search the file I linked for "hires" to find all the places the check is made.

**Comment by byuu** [comment]
Air Strike Patrol force-disables the fast PPU in order to render the plane shadow. Filters like HQ2x won't work when rendering at 512x480. There's no workaround for that.

**Comment by jjfmz42015** [comment]
> Air Strike Patrol force-disables the fast PPU in order to render the plane shadow. Filters like HQ2x won't work when rendering at 512x480. There's no workaround for that.

Im just pointing out bsnes-mcfly accomplishes this with your bsnes 106.xx core

**Comment by jjfmz42015** [comment]
maybe he uses a trick? maybe its bad to do?

**Comment by byuu** [comment]
It's too much of a burden for one game. I'm going to have to decline this one, sorry.

**Comment by Screwtapello** [comment]
> for one game

I mean, people have been complaining about software filters not working on hires/interlaced games since the days of ZSNES, and A.S.P. definitely wasn't the only game with the problem.

On the other hand, we have shaders now, which are much more flexible and useful, so I guess it doesn't make as much sense to spend time on software filters.

**Comment by jjfmz42015** [comment]
It's ok. Thanks anyway. Love the emulator as is and appreciate everything. I only asked in case it was a simple thing. I feel lucky to even have access to bsnes at all. Thanks for the new release!!
