### ISSUE TITLE
OpenGL 3.2 Fullscreen Screenshots result in a black screen since v109 release.

### ISSUE THREAD

**Issue by hchorey** [byuu/bsnes#110]
Sometime between the v108 release and the v109 release, taking a print screen screenshot when in fullscreen mode using OpenGL 3.2 results in a screenshot consisting of a completely black screen instead of the expected screenshot output, which was working in v108.

v108 vs. v109 screenshots here: https://twitter.com/hchorey/status/1172519797076176897

Windows 10 using OpenGL 3.2; I downloaded v108 to compare against and full screen screenshots work in 108.

**Comment by byuu** [comment]
That's likely because v109 is triggering true exclusive fullscreen mode (for adaptive sync.)

I don't think it's going to be practical to fix that, it'd probably require hooking the print screen key and replacing the clipboard with a copy of the internal emulation screen image, which is way too much work.

I'll leave this open a bit in case anyone else has other ideas, but leaning toward a no on this one, sorry. I could add a hotkey for the emulator screen capture function if you wanted though.

**Comment by hchorey** [comment]
> I could add a hotkey for the emulator screen capture function if you wanted though.

That would be great; it doesn't have to be hooked to Print Screen, but being able to have something in addition to the existing (SNES) 256px x 224px screenshot functionality would be perfect.  :)

**Comment by byuu** [comment]
The hotkey for screenshots is in, and it writes to a file. Can be bound to print screen. That's about as good as this will get with no outside interest, so I'll mark this one resolved for now.
