### ISSUE TITLE
Crash when closing bsnes without prior loading any game

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#114]
bsnes v109 (including the latest v109.3) crashes on close. This happens _regardless_ of video and audio drivers (tried all of them including “None”).

bsnes **stops** crashing after switching the Input driver (Settings → Drivers → Input) from the “Windows” value to the “None” value.

bsnes v107 and v108 seem to be affected too, but differently: bsnes does not crash itself on close, but after several restarts it says that a driver crashed and automatically resets all three drivers (Video, Audio, Input) to “None”.

* OS: Windows 7 Home Premium SP1 (build 7601) (64-bit).
* CPU: Core i3-2100T.
* RAM: 8 GB.
* GPU: nVidia GTS 250 (2GB) with driver v342.01 (the latest one with support for GTS 250).
* Keyboard: Logitech “K120 for Business” with the standard Windows driver. Fwiw, the keyboard is listed as two identical HID devices in the Windows device manager.

**Comment by byuu** [comment]
I need a backtrace if you want me to fix this.

**Comment by Marat-Tanalin** [comment]
How to get a backtrace?

**Comment by xZabuzax** [comment]
Since the thread was created again I will post my findings regarding this issue here. I already posted it in the old thread but here it is:

The crashes always happen on the conditions I will provide below. This is what I've found so far regarding v109:

- OpenGL 3.2 + audio drivers doesn't cause any crash. (ASIO is the only one crashing)

- Direct3D 9.0 + ASIO, DirectSound 7.0 and waveOUT cause the crash. It doesn't crash with XAudio 2.1 and WASAPI.

- DirectDraw 7.0 + ASIO, DirectSound 7.0 and waveOUT cause the crash. It doesn't crash with XAudio 2.1 and WASAPI.

- GDI + ASIO and DirectSound 7.0 cause the crash. It doesn't crash with XAudio 2.1, WASAPI and waveOUT.

For some reason v109.3 was not crashing in the beginning but now it started to crash again, it will always crash with the conditions I will provide below:

- Selecting any video driver + XAudio 2.1 is the combination that is crashing now on v109.3. (XAudio is the culprit here)

However, if you enable the snow effect and select in the driver Input "None" then the results are different:

- OpenGL 3.2 + any audio drivers causes the crash.

- Direct3D 9.0 + any audio drivers causes the crash.

- DirectDraw 7.0 + WASAPI and waveOUT doesn't crash. It crashes with the other audio drivers.

- GDI + WASAPI doesn't crash. It crashes with the other audio drivers.

I don't know why v109 and up is crashing for me, v108 and below never crashed even once.

**Comment by Screwtapello** [comment]
I don't know how it works on Windows, but here's how it works on Linux:

- Install GCC so you can compile bsnes from source. The [instructions in the higan docs](https://higan.readthedocs.io/en/stable/install/windows/#compiling-from-source-on-windows) are a bit old, but probably still work.
- Grab a copy of the bsnes source-code either by checking it out with git, or going to the main page of the GitHub repo, clicking the big green "Clone or Download" button on the right, and choosing "Download ZIP" at the bottom of that menu
- Build bsnes in debug mode by opening a command prompt and:

        cd c:\place\where\you\extracted\the\bsnes\source\
        mingw32-make -C bsnes build=debug

- Run the freshly-built debug build from the same command prompt:

        bsnes\out\bsnes.exe

- verify that it still crashes in the same ways at the same times (if it doesn't, generating a backtrace won't help)
- Still in the same command prompt, start debugging the debug bulid of bsness inside the gdb debugger:

        gdb bsnes\out\bsnes.exe

- Once gdb has started and gives you a `(gdb)` prompt, type `run` and hit Enter to actually start running bsnes.
- When bsnes crashes, it may freeze instead of disappearing. The window where gdb is running will probably say something like "Thread #0 received SIGSEGV" and display another `(gdb)` prompt. Use the `bt` command to generate a backtrace showing exactly where the problem occurred. [byuu's comment from the previous thread](https://github.com/byuu/bsnes/issues/100#issuecomment-529472044) shows a typical gdb session copy/pasted into Notepad

**Comment by jjfmz42015** [comment]
Have never had bsnes 108 or 109 crash on 3 of my systems all very different setups. Could it be something he is running causing conflict?

**Comment by byuu** [comment]
Well, if someone can get me a backtrace I'll look into it, and feel free to reopen this, but otherwise I can't reproduce this.

**Comment by Marat-Tanalin** [comment]
Closing unfixed bugs is an interesting approach. Did you at least try to look into code related to what I _described_? A backtrace is actually the _last resort_, not the only way to fix bugs.

Some additional info based on testing on my second computer: bsnes v109 craches too, though more rarely, and looks like the probability of a crash gets higher as the time between bsnes start and close gets shorter. In other words, the faster bsnes is closed after start, the higher the probability of crash is.

Note that such crashes happen under Windows **7**. Under Windows **10**, bsnes v109 itself doesn’t crash (W10 probably suppresses such crashes happening when the app is closed anyway), but  after several restarts bsnes says that a driver crashed and automatically resets all three drivers (Video, Audio, Input) to “None” — just like v107 and v108 under Windows 7.

**Comment by orbea** [comment]
> A backtrace is actually the last resort, not the only way to fix bugs.

A backtrace is step one when debugging crashes, especially when the developer can not reproduce it...

**Comment by Marat-Tanalin** [comment]
Depends on developer. Are there prebuilt debug binaries of bsnes for Windows?
