### ISSUE TITLE
Heisei Inu Monogatari Bow - Pop'n Smash!! (Japan) - flickering [bsnes v110]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#123]
Hardware: https://streamable.com/fkvns

bsnes (Fast PPU on and off), higan v106, snes9x, Mesen-S: https://streamable.com/1gg05

**Comment by byuu** [comment]
Are you 100% sure the top scanline isn't just being cut off by your TV?

**Comment by Max833** [comment]
Oh, I didn't think anything of it. Is there a way to test this?

**Comment by byuu** [comment]
Tagging @SourMesen

So this game starts NMI at the usual V=225. It does a bunch of small things, and one DMA transfer, and runs until V=0,H=~218 before waiting until we're no longer in Hblank, and then waiting again until we are.

Because it's at V=0,H=~218, this means the "wait for next Hblank" loops puts us at V=1,H=>1096. It then enables the display, so the display starts drawing as of scanline 2.

It doesn't always do this, it depends on the DMA transfer length.

If we overclock the CPU by even 1%, it gives it enough time so that the NMI routine always ends before V=0,H>1096.

I have about ~80% confidence this will happen on real hardware, and the top scanline is just getting cut off by your TV. Because if it doesn't, it means that in 38 scanlines, every single SNES emulator out there is off by more than 218 clock cycles, which is pretty much nonsensical (famous last words.)

So at this point, we need someone with real hardware and the ability to control overscan to confirm what happens on the very topmost scanline.

Normal CPU speed trace log:

[trace-bad.log](https://github.com/byuu/bsnes/files/3639795/trace-bad.log)

1% overclock CPU speed trace log:

[trace-good.log](https://github.com/byuu/bsnes/files/3639796/trace-good.log)

**Comment by Pat86** [comment]
Happens on real hardware as well

https://www.dropbox.com/s/dcswjktyylkfuuj/MOV_0013.mp4?dl=0

**Comment by byuu** [comment]
Thank you so much for verifying! Nicole also verified, so we'll mark this as a real game bug as predicted. Thanks for the report all the same.

If I ever get around to that "known hardware bugs" page, I'll add this game to it.

**Comment by nicolebranagan** [comment]
For posterity, here's a quick capture from my SNES Jr. that also shows the issue https://nicole.express/other/heisei-inu.mp4
