### ISSUE TITLE
Full Throttle - All-American Racing (USA) (Beta) - Scanline Timing [bsnes v110.2][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#127]
bsnes: https://abload.de/img/1122d1jsf.jpg
Hardware: http://abload.de/img/f62115a9-abb9-40c6-8wyk0e.jpeg

**Comment by byuu** [comment]
It's writing to the PPU registers later into the scanline.

I am hesitant to fix this one because it's beta software. If I open the door to unlicensed software, then it will be hard to say no to ROM hacks, homebrew, etc.

So for now I am going to mark this as wontfix, but a future enhancement could be to allow exposure of overrides into manifest files, so that people can apply these kinds of fixes to unlicensed software as well.
