### ISSUE TITLE
[Super Game Boy] sound issue after rewinding

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#143]
https://streamable.com/89haj

**Comment by byuu** [comment]
My fix for getting the audio clean only worked part of the time.

@LIJI32 I really need your help with this. Sound being troublesome in every single SGB game is much worse than benderscruffy's 20 bug reports with my core. The last SGB sound issue was an open bug for over two months. I'll give it another month, but if we don't have this solved by November, then I don't really have a choice but to go back to higan's Game Boy core.

The relevant code is here:

https://github.com/byuu/bsnes/blob/master/bsnes/sfc/coprocessor/icd/icd.cpp#L42

Presuming the SGB2, I set the audio frequency to (20*1024*1024)hz / 5.0 / 128 -> eg (4*1024*1024) / 128 -> eg 32768hz. I call GB_set_sample_rate(32768).

When the ICD register $6003.d7 is set, that means the ICD is suspended, and I still need to generate periods of silence so that the SNES DSP doesn't stall waiting on the Game Boy core to generate more samples.

So with the clock running at the 4MHz rate, it should be one sample every 128 clocks. 4MHz/128 = 32768hz. But this is completely distorting sound, and your core is slowly generating more samples than it should.

Your core is outputting 8MHz clock rates (probably for GBC emulation), and so I erroneously thought a wait of 256 clocks on $6003.d7 was the fix, but it's not. The boot sequence runs at double speed like that, and I hadn't noticed.

As your core is running, the audio resampling buffer for it keeps growing and growing, meaning it's generating audio samples a little bit too quickly, which is causing the tiny buffers I keep for audio resampling to constantly overflow and cause crackling.

Please lend a hand if you can.

**Comment by LIJI32** [comment]
I'll have to take a better look, but the sampler *should* output the exact rate requested. I'm not sure why 32000Hz audio seems to fix it for you as it should make it sound worse.
