### ISSUE TITLE
dead zone is needed for game controller (PS4 over usb)

### ISSUE THREAD

**Issue by mobilevil** [byuu/bsnes#149]
I am mapping L and R buttons to PS4's L2 and R2 triggers, the setup screen take the buttons fine but in game the L and R buttons are being triggered constantly. I suppose a little dead zone can fix this issue. Thanks for the great work!

**Comment by byuu** [comment]
There is a dead zone, it's half the range of the inputs:
https://github.com/byuu/bsnes/blob/master/bsnes/target-bsnes/input/input.cpp#L136
The range is -32768 to +32767, and the dead-zone is -16384 to +16383.
There's a very difficult problem mapping triggers though, it sometimes registers them as ".Lo" or ".Hi", and it's possible it mapped the trigger the wrong way for you. Try alternating between hitting down the triggers quickly and very slowly, after a few tries you should be able to get it to flip to the other direction.
It's a bit of a pain I know, but gamepad APIs don't tell you which direction is which, and it's not consistent.

**Comment by mobilevil** [comment]
hi,
what if we consider a dead zone in the gamepad setup screen?

**Comment by byuu** [comment]
The GUI is already getting too complicated, but maybe there's a better way to map gamepad triggers. Worst case, a database of product IDs to auto-select the trigger direction.

**Comment by byuu** [comment]
I can't think of a better way of handling this, so I'm going to close this as cantfix, sorry.
If someone thinks of a better system I'm willing to consider it.
The crux of the issue: gamepad APIs like SDL and DirectInput just treat gamepad triggers as axes, but don't tell you which direction the button is supposed to be pressed in, and I'm not at this time willing to go to the pain of having a database of every gamepad ever made to try and add this missing functionality (and even then, I kind of can't since SDL doesn't report product/vendor IDs for gamepads.)
