### ISSUE TITLE
Lost Vikings 2 (USA) and Lost Vikings, The (USA)

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#153]
I'm not 100% sure that this has something to do with rewind (https://github.com/byuu/bsnes/issues/150), but before the second attract mode level starts, bsnes freezes. And... I couldn't reproduce this with rewind disabled.

https://streamable.com/np4ed

**Comment by byuu** [comment]
I'm just going to have to give up on rewind as a reliable feature, sorry.
I cannot implement 100% save save states that work in every game.

**Comment by Max833** [comment]
> I'm just going to have to give up on rewind as a reliable feature, sorry.

I mean... it's understandable. I'll write them down and let you know when I'm done. :)

**Comment by byuu** [comment]
Yeah, if I fix Lost Vikings I will just end up breaking different games.
There is no solution, so let's just try and sequester the issue to less important titles.
We'll keep track of them so that maybe in the future we can have a dozen serialization methods and have per-game overrides to select a serialization strategy.
