### ISSUE TITLE
[question] Filter vs. shader?

### ISSUE THREAD

**Issue by tuzepoito** [byuu/bsnes#179]
**Software** bsnes v111r9
**Platform** Windows 8.1

I know this is more a question than a real issue, but...

I am not too sure about the distinction between a graphical *filter* and a *shader* (from the "Settings" menu) and could not find much from the documentation either. They seem to achieve similar things, it gives me a feeling of redundancy.

An illustrating example being the existence of both NTSC filters and NTSC shaders. One can even apply both at the same time, which makes little sense to me. The "Blur" shader also seems a bit separate from the rest - given its specific effect.

On a personal note I use both the "NTSC-RGB" *filter* and "Blur" *shader* as this is the combination which appears to achieve what I want.

Anyway, good job on the emulator and your dedication to the work! Keep going!

**Comment by Screwtapello** [comment]
The SNES renders each video frame at a particular resolution, either 256×240, 512×240, 256×480, or 512×480.

A "filter" is a program that runs on the CPU and converts a 256×240 image to a 512×480 image.

A "shader" is a program that runs on the GPU, and converts any size image to any size image.

They're similar, since they can both synthesise detail when upscaling an image, making a tiny SNES image on a huge PC monitor look less blocky or blurry.

A filter can work on computers with an older or weaker GPU, and some visual effects are much easier to implement as fixed-ratio filters than arbitrary-scaling shaders.

On the other hand, a shader works all the time, not just when the SNES displays 256×240 input images, and can scale an image up to full 4K resolution, not just 512×480.

Given that every PC modern enough to run bsnes has a GPU powerful enough to run at least the simpler shaders (that includes Intel Atom CPUs with integrated graphics, not just high-end gaming rigs), there's not much use for filters these days... but because other SNES emulators have them, and because they're kind of traditional, they were put into bsnes.

**Comment by tuzepoito** [comment]
Thanks, it makes sense. I had forgot how filters were originally meant for pixel-wise processing such as hq2x, SuperEagle or SuperSAI, while shaders usually handle more complex / generic graphical stuff. I actually think some CPU-side filters can still have their own purpose, like how you described with fixed-ratio processing.

Now, as I said before, the wording and the lack of documentation can create some confusion among users about the purpose of either function, not to mention seemingly redundant features like the NTSC filters. I'm also wondering whether the "Blur" shader is an actual shader or simply another wording of the classic "Bilinear filtering" parameter. All in all I'd say what is most needed is documentation about this - though I do realize the software is apparently still in beta.

**Comment by Screwtapello** [comment]
For historical reasons, the "nearest neighbour" and "bilinear" upscaling algorithms (or as bsnes calls them, "None" and "Blur") are built into the GPU, or at least into the OpenGL and Direct3D APIs. They're not shaders in the sense that bsnes doesn't need to upload an algorithm to the GPU to make them work, but they're very much shaders in the sense of "the GPU follows instructions for interpolating missing data".

I agree that bsnes could do with more documentation, but it's a matter of finding people with the time and skill to work on it.

**Comment by jjfmz42015** [comment]
All my windows 7 and 10 machines Intel IGP and Nvidia seem to perform better in direct3d than open gl. The shaders don't work in direct 3d. For this filters are helpful
