### ISSUE TITLE
Firearm (USA) (Proto) (1993-12-17) [v111.10]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#184]
I totally forgot to report this game.

hardware:
http://streamable.com/dxxit
![image](https://user-images.githubusercontent.com/53529402/67143347-e1c8d000-f26a-11e9-8751-879d5563ba17.png)

bsnes:
![image](https://user-images.githubusercontent.com/53529402/67143284-33bd2600-f26a-11e9-8e7d-592186a17875.png)

**Comment by byuu** [comment]
Please, no demos or prototypes. Please.

**Comment by CharlesCorrin** [comment]
I agree bsnes shouldn't need to support demos or protos. That rabbit hole would be deep. But I think we could still ask WHY this game doesn't work correctly in bsnes, but does on a real SNES. Is it because of unsupported mapping or because bsnes isn't emulating some SNES quirk correctly? If it's the latter, I think it's worth attention. But if it's the former, then of course one should carry on by all means. :3

But probably I'm not saying anything you haven't already considered.
