### ISSUE TITLE
Run ahead breaks tepples' "Telling LYs?" test ROM

### ISSUE THREAD

**Issue by Screwtapello** [byuu/bsnes#212]
tepples published a test ROM [on NesDev](https://forums.nesdev.com/viewtopic.php?f=12&t=19435&p=243608#p243608) ([mirror](https://gitlab.com/higan/snes-test-roms/tree/master/tepples-tellinglys)), which tries to detect an emulator by polling the gamepad as quickly as possible and checking the current scanline whenever a button-press is detected. For most emulators that poll once per frame, every button press will be on the same scanline, but on real hardware a button press can be detected anywhere in the frame.

bsnes v112.7 passes this test beautifully for me... but only if "run ahead" is disabled. When it's enabled, the ROM immediately dismisses the title screen (instead of waiting for a button press) and fails to display the button icons at the bottom of the screen, or the speech-bubbles in the middle:

![image](https://user-images.githubusercontent.com/1450918/68104053-8f0b3b80-ff2d-11e9-945e-6cd9c085d45a.png)

Since this is a homebrew ROM and not officially licensed, I don't expect this bug to be fixed, but it's puzzling to me why run-ahead breaks this ROM so badly, when the whole point of run-ahead is to be invisible to the emulated game.

**Comment by byuu** [comment]
The issue is the just-in-time polling polls with a 5ms -real time- timeout. Run-ahead accelerates the emulation speed so instead of the games polling every 16ms, they poll every 8ms at run-ahead=1, every 6ms at run-ahead=2, etc. I'll expose an option to increase the polling rate, but I don't really think this is that important unless you're at run-ahead=3 or higher.

I don't know or care to research why this particular demo is displaying a blank screen with run-ahead enabled, however.
