### ISSUE TITLE
[feature request] predictive text

### ISSUE THREAD

**Issue by bajolzas** [byuu/bsnes#23]
There's a feature most other emulators have that bsnes still lacks, that is text prediction (dont know if this has another specific name).
Like when Im searching for a specific game in a folder and I type, say S, the emulator will show me the results that match, like super mario world, super metroid, etc...
This makes it so much easier to select any given game.

**Comment by byuu** [comment]
I'd like to have this, but the custom WC_LISTVIEW draw code prevents keyboard shortcuts from working. I have been unable to implement this, and I need the custom draw code. So getting this will require the help of another person.

**Comment by xZabuzax** [comment]
I was about to create the same thread, I'm glad to know that someone pointed this out. Browsing for a specific game in bsnes is indeed a tremendous pain in the ass.

This feature is a must on an emulator and is a feature that existed for decades, can't believe how bsnes is lacking this feature in 2019... come on now... I appreciate all your efforts over these years byuu, you are a necessity in this community but I need to point this out, bsnes is becoming a chore to use because is lacking a simple feature like that.

Sure I can use other emulators (I'm still using Snes9x) but you should know that plenty of other people are unhappy about this as well even if they don't say anything about it and making a transition from another emulator into bsnes is going to be hard because of it.

That's my constructive criticism, sorry if I sounded like an ungrateful bastard, that's wasn't my intention, I'm very grateful to all the hard work you provided in the emulation community and believe me, I didn't wanted to point this out but seeing this issue being ignored for so long in 2019 is actually a big thing in my opinion.

**Comment by byuu** [comment]
![EAvLdzBU4AEsIwp](https://user-images.githubusercontent.com/2107894/62147863-71797500-b333-11e9-9184-2e3c1fee6fa5.png)

Here you go, it'll be in the next nightly build. It's a bit slow to filter and repopulate potentially 10,000+ files -> list box entries with icons on each key press, but not a lot I can do about that.

**Comment by bajolzas** [comment]
thx

**Comment by xZabuzax** [comment]
Thanks, this feature will make the use of bsnes a lot more enjoyable. This is a simple feature that could have been resolved with simple lines of codes.

I mean, even Zsnes had that feature decades ago in the late 90s so if something like Zsnes had it then there's no reason why bsnes couldn't have it as well, seeing bsnes lacking that simple feature this late in 2019 was extremely mind boggling.

Thanks for your hard work mate.

**Comment by Screwtapello** [comment]
> This is a simple feature that could have been resolved with simple lines of codes.

If it were that easy, it would have been done years ago. 

byuu appreciates your thanks, but don't belittle him in the same message - that's a dick move.

**Comment by xZabuzax** [comment]
> > This is a simple feature that could have been resolved with simple lines of codes.
> 
> If it were that easy, it would have been done years ago.
> 
> byuu appreciates your thanks, but don't belittle him in the same message - that's a dick move.

You're programming emulators which is way harder than adding simple features like that, maybe it isn't as easy as I thought it would be but still, the reason bsnes didn't had that feature before wasn't because of the complexity of it, it was simply because that feature was not in the priority list. The moment someone actually brought this up this issue was fixed right away.

I may sound like a dick sometimes but the reason I brought this up in this manner was because I'm interested in bsnes as well and seeing how this issue was being ignored for so long made me into a dickish person in this thread, I apologize for that.
