### ISSUE TITLE
Support all platforms using Web Assembly

### ISSUE THREAD

**Issue by MurhafSousli** [byuu/bsnes#244]
Hi! Great work on this project

I am wondering if you have thought about porting this emulator to the web using Web Assembly? 

This will make it work on any machine that runs a web browser, making it work on all platforms out of the box (Mac, iOS, Android, Ubuntu and Windows) with native performance.

And would also fix #234 and #238 

Moreover, with PWA we can make it run just as a native app (full-screen without the address bar) for iOS and Android, users will be able to play it on iPhone without the need to jailbreak their phones and apple won't be able to block the app since it is web-based

This won't be a hard task, It could be as simple as executing a single command-line, we just need to compile this project with [Emscripten](https://emscripten.org/) and then JS will be able to communicate with C++

I was able to compile a hello-world.cpp to wasm, but couldn't make it with medium/large projects that contains many files/directories due to my lack of knowledge in C++.

- [WebAssembly simple demo](https://timhutton.github.io/opengl-canvas-wasm/)
- [WebAssembly intro video](https://www.youtube.com/watch?v=ysFJHpS-O08)

RetroArch has a port on the web, it has great performance but their UI sucks and isn't mobile friendly

- [RetroArch on the web](https://web.libretro.com/)
- [RetroArch emscripten makefile](https://github.com/libretro/RetroArch/blob/master/Makefile.emscripten)

I would like to contribute to this project with my web skills, If anyone is interested in collaborating on this feature, please let me know!

**Comment by Screwtapello** [comment]
bsnes has come as far as it has because of the time that byuu has put into hiro, the GUI library that wraps GTK+ (on Linux), Cocoa (on macOS), and Win32 (on Windows). Unfortunately, the Web platform doesn't offer anything like those facilities, so bsnes would need a whole new custom user-interface to be written, maybe something much like RetroArch's UI. That would be a lot of time and effort, and definitely not easy.

The bigger problem, though, is that bsnes' emulation core is built around the libco coroutine library, which is *not* written in C++ or C, but in hand-coded assembler for each of the dozen or so platforms it supports. Since WebAssembly is built on a much stricter model than most CPU architectures, I'm not sure it's even possible for libco to be ported to WebAssembly. Apparently [as of 2017](https://stackoverflow.com/questions/44263019/how-would-setjmp-longjmp-be-implemented-in-webassembly) that kind of thing was completely impossible. That StackOverflow answer mentions that a solution is in the works, but "It does not, however, allow the undefined behavior case of jumping forward to a stack that was already unwound which is sometimes used to implement coroutines" which is the kind of thing libco does all the time.  It seems the WebAssembly design repo [lists coroutines as a "future feature"](https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#coroutines) under the heading "Proposals we might consider in the future", so it's almost certainly too early to be thinking about porting bsnes to wasm today.

**Comment by MurhafSousli** [comment]
@Screwtapello  For the first part, I think there would be no need for the UI at the C++ side and the GTK+ can be removed completely.

A config input at the C++ side can be used instead which will be set by the web UI.

For the bigger problem, I had no clue about the _libco coroutine_ library. I just saw the snes9x and many of other game emulators had been ported to web assembly successfully as the case in RetroArch.

Thanks for the feedback, it is good to know that.
