### ISSUE TITLE
[Accurate and fast PPU issue] Taikyoku Igo - Goliath (Japan) - start button doesn't work [bsnes v113.1]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#256]
This one is weird. I can't start the game, because the start button doesn't work. Same with higan v106. 

It works with SNES9x and Mesen-S.

![image](https://user-images.githubusercontent.com/53529402/71491675-40459800-2832-11ea-9915-7002f66b78c1.png)

**Comment by byuu** [comment]
Well so much for the remainder of my vacation ^^;

**Comment by byuu** [comment]
Mesen-S and Snes9X don't emulate auto joypad polling cycles. $4218-421f are populated by reading from the controllers once every 256 cycles, sixteen times, for 4096 cycles or ~3 scanlines.

This game reads the joypads during the auto joypad polling phase because the developers didn't read the SNES developer manual properly.

Three things make it work: reducing the auto-joypad polling to 32 cycles per step (64 is too much), not clearing the joypad shift registers at the start of joypad polling, or forcing the shift register to all 1s at the start of auto joypad polling.

Given the first two are obviously wrong, I'm going with the third option. There was a game that clearing the shift register was required to work with, but unfortunately I don't remember what it was, and I can't find it anywhere (it might be mentioned somewhere in the changelogs from around two years ago possibly.) Well, hopefully whatever that game was will still work with 1s instead of 0s.

Fixed for now. Let's see what happens.

**Comment by Max833** [comment]
Thanks byuu.

They ("Taikyoku Igo - Goliath" and "Nuke (PD)") work on my real SNES. With bsnes 113.2 Taikyoku igo works, but not Nuke. And with 113.1... well, the other way around.

But there is another game that works now better: SpellCraft - Aspects of Valor. When you press b at this place, you get to the password menu... with 113.1 this didn't work and now... it's perfect.

![image](https://user-images.githubusercontent.com/53529402/71528566-b9032d80-28e0-11ea-9701-2e52b0f93921.png)
![image](https://user-images.githubusercontent.com/53529402/71528645-1ac39780-28e1-11ea-9b6a-27f603aa9f8b.png)
