### ISSUE TITLE
filters such as 2xsal only work on fast ppu

### ISSUE THREAD

**Issue by jjfmz42015** [byuu/bsnes#27]
filters such as 2xsal only work on fast ppu

**Comment by byuu** [comment]
That's unfortunately correct. It will only work with the fast PPU, because the accurate PPU only renders at the full 512x480 resolution. I'll add code to disable the filters so that this doesn't cause confusion, thanks for the report.

**Comment by jjfmz42015** [comment]
Thanks for the confirmation

**Comment by jjfmz42015** [comment]
somehow in bsnes mcfly the filters work with dot ppu. Why does it work there? what is the disadvantage?

**Comment by Screwtapello** [comment]
I don't know exactly how bsnes-mcfly does things, but the issue is that the SNES can change horizontal resolution (ruining filters like HQ2x and 2xsai) at any point in the frame, maybe even part-way through a scanline. Filters require the entire frame to be at the same resolution. Therefore, the choices are:

  - Have the emulation core always output the maximum resolution, which means all hardware quirks can be accurately emulated but filters don't work
      - higan does this
  - Have the emulation core filter fully-low-res frames, leave fully-high-res frames unmodified, and assume mixed-res frames will never happen in practice
      - Snes9x, modern bsnes' Fast PPU, older versions of bsnes, and maybe bsnes-mcfly do this
- Keep track of which scanlines are drawn low-res and which scanlines are drawn high-res and filter them independently, which means filters work as well as they can and hardware accuracy is much higher, but the emulator as a whole becomes much, much more complex to write and difficult to maintain
      - As far as I know, nobody does this

When you turn off "Fast PPU", you're opting into higan-tier accuracy, and losing access to filters is part of the cost.

As for why older versions of bsnes worked this way and higan doesn't, byuu didn't always understand all the details of how the SNES PPU works. As he learned more, it became more and more difficult to handle all the details with the old system, and so he changed to the new system.

**Comment by jjfmz42015** [comment]
Thanks for the detailed explanation. I only asked to learn a little. I find this stuff interesting!
