### ISSUE TITLE
Exclusive fullscreen mode is forced on and can't be changed 

### ISSUE THREAD

**Issue by katawful** [byuu/bsnes#273]
I have multiple monitors so exclusive mode isn't something I want to use, yet I can't seem to change the setting in the GUI and forcing it off in the config file doesn't seem to do anything. I've had this issue with v112 and v113

Some other info:
OS: Manjaro 18.1.4 Juhraya
Kernel: x86_64 Linux 5.4.6-1-MANJARO
DE: KDE 5.65.0 / Plasma 5.17.4
WM: KWin
CPU: Intel Core i5-4690K @ 4x 4.4GHz
GPU: Radeon RX 570 Series (POLARIS10, DRM 3.35.0, 5.4.6-1-MANJARO, LLVM 9.0.0)

**Comment by Screwtapello** [comment]
My understanding is that the only driver that supports both "exclusive" and "non-exclusive" modes is the Direct3D driver. In particular, the POSIX OpenGL driver [just forces "exclusive" mode to always be on](https://github.com/byuu/bsnes/blob/892f202945879f644e5535a383d241db1c7c3bdc/ruby/video/glx.cpp#L15-L19), but modern OpenGL doesn't really have any notion of "exclusive" mode (or even "fullscreen" mode for that matter). I think if it force-disabled "exclusive" mode instead of force-enabling it, it would still behave in exactly the same way.

I don't have multiple monitors, so I'm not sure what you expected exclusive mode to do, or why you think disabling it would help.

**Comment by katawful** [comment]
byuu remarks that exclusive fullscreen takes over the entire display area, and there are ways to get "exclusive fullscreen" equivalent with x11 which is what I imagine is the case here. I can't turn this feature off, my second display doesn't display anything once in fullscreen which is not what I want. I don't care about latency from basic fullscreen. I'm just confused why I can't seem to turn this off

**Comment by byuu** [comment]
Unfortunately on Linux it's not possible to do a non-exclusive fullscreen mode. In order to get a borderless window (necessary for G-sync to work), I have to use the CWOverrideRedirect flag. Apologies, but this one's a cantfix.

If anyone comes up with something else though, please send a pull request or feel free to reopen this work a suitable workaround. Sorry about this.
