### ISSUE TITLE
Feature Request: Allow to MSU-1 Games to work from Winzip

### ISSUE THREAD

**Issue by FuxorLuck** [byuu/bsnes#293]
Hello

I don't like to have a folder with all the game files so i use winrar to change the game folder to Winrar zip archive.

By doing so I can still boot the game but the MSU-1 chip doesnt work.

Is there anyway to make it possible?

Thanks

**Comment by Screwtapello** [comment]
The MSU-1 feature allows the game to request pretty much any data at any time. If the data is uncompressed, that's easy. If the data is compressed, then it needs to be uncompressed on-demand (which is likely to add a *lot* of crackle and stutter) or it needs to be uncompressed when the game is first loaded, which could potentially take a *lot* of RAM and/or disk space.

It's reasonable for non-MSU-1 games to be compressed, because at most they're a couple of megabytes uncompressed, which isn't a big deal on modern computers. MSU-1 games, however, can be *gigabytes*, which can still be a big deal.

**Comment by byuu** [comment]
Yeah, the MSU1 data file alone can weigh in at up to 4GB. It's too much to try and allocate that all at once (and isn't even possible on a 32-bit system.) Just like with higan's CD-ROM support, it absolutely needs to be decompressed to run.
