### ISSUE TITLE
Feature Req: Print ROM manifest to command line

### ISSUE THREAD

**Issue by quinton-ashley** [byuu/bsnes#299]
Hi I'm working on getting my front end Nostlan to support bsnes.  I would like to be able to identify ROMs by their manifest data.  It'd be great if their was a command line option that printed the ROM's manifest to the console!  I would try to add this to bsnes myself but I don't know where to start.

**Comment by byuu** [comment]
I won't do this upstream because it spams the console window, but:

https://github.com/byuu/bsnes/blob/master/bsnes/emulator/game.hpp#L50

Add print(text); here. Hope this helps! ^-^

**Comment by quinton-ashley** [comment]
Thank you! Ideally I was hoping this could be merged upstream and it would only print to the console if the user used `--info` as a command line option.

**Comment by quinton-ashley** [comment]
Seems like it might be a trivial task for you but if you'd rather not spend time implementing that let me know.  Alternatively if you could send me a build of bsnes with that print(text) added that'd be not as ideal but it would get the job done.

**Comment by Screwtapello** [comment]
Does it have to be bsnes? Builds of higan include the `icarus` tool, which has a (semi-secret) command-line option to print the ROM manifest:

```console
$ ./icarus/out/icarus --system "Super Famicom" --manifest ~/Emulation/Super\ Famicom/Super\ Mario\ Kart\ \(USA\).sfc/program.rom 
game
  name:     program.rom
  label:    program.rom
  title:    SUPER MARIO KART
  region:   USA
  revision: 1.0
  board:    NEC-HIROM-RAM
    memory
      type: ROM
      size: 0x80000
      content: Program
    memory
      type: RAM
      size: 0x800
      content: Save
    memory
      type: ROM
      size: 0x1800
      content: Program
      manufacturer: NEC
      architecture: uPD7725
      identifier: DSP1B
    memory
      type: ROM
      size: 0x800
      content: Data
      manufacturer: NEC
      architecture: uPD7725
      identifier: DSP1B
    memory
      type: RAM
      size: 0x200
      content: Data
      manufacturer: NEC
      architecture: uPD7725
      identifier: DSP1B
      volatile
    oscillator
      frequency: 7600000
```

**Comment by quinton-ashley** [comment]
oh wow, this is perfect!  I'll just require Nostlan users to also have higan.  Thanks!

**Comment by quinton-ashley** [comment]
That's not the same manifest that bsnes uses.  I really need is a way to identify the rom with a unique id and get their proper name of the game.  icarus won't work for this purpose.

icarus manifest
```
game
  name:     Super Mario World (U) [!].smc
  label:    Super Mario World (U) [!].smc
  title:    SUPER MARIOWORLD
  region:   USA
  revision: 1.0
  board:    LOROM-RAM#A
    memory
      type: ROM
      size: 0x80200
      content: Program
    memory
      type: RAM
      size: 0x800
      content: Save
```

bsnes manifest with the proper name of the game and unique identifiers
```
game
  sha256:   0838e531fe22c077528febe14cb3ff7c492f1f5fa8de354192bdff7137c27f5b
  label:    Super Mario World
  name:     Super Mario World
  region:   SNS-MW-USA
  revision: SNS-MW-0
  board:    SHVC-1A1B-06
    memory
      type: ROM
      size: 0x80000
      content: Program
    memory
      type: RAM
      size: 0x800
      content: Save
  title: SUPER MARIOWORLD

board: SHVC-1A1B-(04,05,06)
  memory
    type:ROM
    content:Program
    map
      address:00-1f,80-9f:8000-ffff
      mask:0x8000
  memory
    type:RAM
    content:Save
    map
      address:70-7d,f0-ff:0000-ffff
```

**Comment by quinton-ashley** [comment]
This is awesome! ...but it doesn't work .smc files.  What's the best way to convert an smc file to sfc?

**Comment by quinton-ashley** [comment]
Disregard my other responses.  This will work! Thank you!

**Comment by quinton-ashley** [comment]
Okay I do have one other question sorry.  On macOS when I run icarus using wine with a Super Mario World smc file I get this:

```
wine icarus.exe --system "Super Famicom" --manifest /Users/qashto/Documents/emu/bsnes/GAMES/Super\ Mario\ World\ \(U\)\ \[\!\].smc
game
  name:     Super Mario World (U) [!].smc
  label:    Super Mario World (U) [!].smc
  title:    SUPER MARIOWORLD
  region:   USA
  revision: 1.0
  board:    LOROM-RAM#A
    memory
      type: ROM
      size: 0x80200
      content: Program
    memory
      type: RAM
      size: 0x800
      content: Save
```

If I use an sfc file I get the full manifest I need:

```
wine icarus.exe --system "Super Famicom" --manifest /Users/qashto/Documents/emu/bsnes/GAMES/Super\ Mario\ World\ \(U\)\ \[\!\].sfc
game
  sha256:   0838e531fe22c077528febe14cb3ff7c492f1f5fa8de354192bdff7137c27f5b
  label:    Super Mario World
  name:     Super Mario World
  region:   SNS-MW-USA
  revision: SNS-MW-0
  board:    SHVC-1A1B-06
    memory
      type: ROM
      size: 0x80000
      content: Program
    memory
      type: RAM
      size: 0x800
      content: Save
```

On windows running icarus with the smc file works and prints out the full manifest with the game name instead of the file name.  How would I get the full manifest for smc files on macOS?  Also I noticed your command has `/program.rom` at the end of the file name but when I add that nothing happens.

**Comment by Screwtapello** [comment]
SNES games, like all cartridge-based games, contain a ROM of game data, and a circuit board that wires up different parts of the ROM to different places in the console's memory-map. To properly emulate a game, you need both the ROM data, and a description of the circuit board.

Back in the 90s when the SNES was still a thing, there were devices called "game copiers" that sat between the console and the game, and had a floppy disk drive. They could read the ROM data from the game and write it to the floppy disk, or read ROM data from the floppy disk and let it run on the SNES, but they also needed information about the game's circuit board to make it work, and they did this by storing an extra 512 bytes of data at the beginning of the file.

There were many different SNES game copiers, and they all used different, incompatible formats for their circuit-board data. The Super Magicom wasn't the most popular, but for whatever reason the GoodSNES database standardised on the `.smc` file extension, regardless of whether the file in question used the Super Magicom header, some other copier's header, or just 512 bytes of gibberish.

As it turns out, for commercially-released games you can 99.9% of the time guess what circuit board a game used by studying the game's internal header, and applying [a bunch of hard-won heuristics](https://github.com/byuu/higan/blob/master/icarus/cartridge/super-famicom.cpp#L44), so for preservation purposes it's better to just ditch the copier header and only store the actual ROM data, which is typically given the `.sfc` file extension.

(The Internet and file-sharing being what it is, the `.smc` extension is not a guarantee that the file has a copier header, and the `.sfc` extension is not a guarantee that the file does *not* have a header. The most reliable way to tell is to divide the file's size by 0x40000 - if the remainder is 512 (0x200), that's a copier header)

Of course, 99.9% of commercially-released games is not 100%, and it definitely doesn't include things like homebrew, so we still need a way to obtain accurate board data, or at least a really good guess, for accurate emulation. icarus is higan's tool for exactly that.

If you invoke icarus like this:

    icarus --system "Super Famicom" --import path/to/some/file

...icarus will examine the file, strip any copier header, extract any embedded firmware files, and write them out with standard names to a standard location (typically `~/Emulation/Super Famicom` but this can be configured in the icarus GUI).

If you invoke icarus with the `--metadata` flag and the path to a previously cleaned and imported file:

    icarus --system "Super Famicom" --metadata path/to/imported/file

...icarus will look up the file in [its internal database](https://github.com/byuu/higan/blob/master/icarus/Database/Super%20Famicom.bml) of game metadata, and if it's not there it will generate metadata heuristically as before.

So:

- in your SMC example, I can see that the file-size is 0x80200. That extra 0x200 indicates there's a copier header, which is confusing matters and preventing icarus from finding its Super Mario World database entry, so you get generic heuristic metadata
- In your SFC example, the file-size is 0x80000, so there's no copier header and icarus gets the correct database entry.

It's probably not practical to fully import a game just to extract the metadata with icarus, but you can just make a temporary copy of the file with the copier-header removed, and use `--manifest` on that.

Which metadata fields do you need for your emulator front-end? The only fields emulators actually care about are the `board` field (which gets looked up in the emulator's [circuit board database](https://github.com/byuu/higan/blob/master/higan/System/Super%20Famicom/boards.bml) and its sub-fields. In particular, "label" is the game's actual original name as written on the box/cartridge, manually recorded by Near himself, so you can't depend on that existing for every game you might want to load.

>  Also I noticed your command has /program.rom at the end of the file name but when I add that with either file nothing happens.

No, in that command `program.rom` *is* the file name, it's just in a directory whose name ends in `.sfc` because that's how `icarus --import` does things.

**Comment by quinton-ashley** [comment]
Wow thank you for this long response!  This is really great info.  You asked why I want to do this and it's because I used the internal manifest database of bsnes to make a custom json database that stores the game info with urls to images of game art scraped from a lot of different sites.  I took the board, region, and revision and combined them into a single unique id.  So Nostlan has to get those from icarus to identify the game.

https://github.com/quinton-ashley/nostlan/blob/master/db/snesDB.json
sample of Super Mario World USA rev 0:
```
{
  "id": "SHVC-1A1B-06-MW-USA-0",
  "title": "Super Mario World",
  "img": {
    "coverFull": "c 3265"
  }
}
```
coverFull is the full cover image of the game http://www.thecoverproject.net/download_cover.php?src=cdn&cover_id=3265 and I wrap the url to only keep the unique portion.

Regarding the `/program.rom` thing, that makes way more sense.  I thought maybe the .sfc was a package folder like a .app on macOS but wine just couldn't open it or something.  I just ran the import and it was really fast so I definitely just want to use that to convert smc files and then delete the og smc.

I have one more question!

you said:
"...icarus will examine the file, strip any copier header, extract any embedded firmware files, and write them out with standard names to a standard location (typically ~/Emulation/Super Famicom but this can be configured in the icarus GUI)."

Is there a way to change that location via the command line or by editing a config file?  If not obviously I can move the game folders out of `~/Emulation/Super Famicom` to the user's game library folder but that'll be slower ofc and they might not have room on their home dir drive for that.

**Comment by Screwtapello** [comment]
>  I took the board, region, and revision and combined them into a single unique id.

If you want to identify a particular game, *probably* the thing you want is the "SNS-MW" part of "SNS-MW-0". For example, the Super Game Boy is exactly identical between the [Japanese](https://byuu.org/preservation/super-famicom-(jpn)/super-game-boy-(sgb)-(1.2)) and [American](https://byuu.org/preservation/super-nintendo-(usa)/super-game-boy-(usa)-(1.2)) releases, so their revision codes both start with "SGB-R". Meanwhile, Chrono Trigger is different (it got translated) so the [Japanese](https://byuu.org/preservation/super-famicom-(jpn)/chrono-trigger-(jpn)-(1.0)) revision starts with "SHVC-ACTJ" while the [American](https://byuu.org/preservation/super-nintendo-(usa)/chrono-trigger-(usa)-(1.0)) revision starts with "SNS-ACTE". You don't need to track the release number, because Donkey Kong Country v1.1 should get the same cover art as v1.0, and the board name is similarly irrelevant.

In fact, the bsnes database is just looked up by SHA256. You could probably write a tool that reads [the icarus game database](https://github.com/byuu/higan/blob/master/icarus/Database/Super%20Famicom.bml), pulls out the SHA256 field and the revision field for each game, trims off the revision number, and writes out a nice simple SHA256 → game code JSON blob. Then your front-end just has to take each file, trim off the copier header if necessary, SHA256-hash the remainder, then look up the game code, and you won't even need icarus around. You might need to re-run the icarus-to-JSON tool again to update the database when future versions of higan are released, but that shouldn't be difficult to do.

> I thought maybe the .sfc was a package folder like a .app on macOS but wine just couldn't open it or something.

Yeah, that's the idea, but higan is cross-platform and other platforms don't support the macOS concept of a "bundle", so icarus just creates an ordinary directory.

> Is there a way to change that location via the command line or by editing a config file?

Yes, icarus stores the import path in a config file. However, the path to the config file can't be changed via the command-line, so if you wanted to mess with it you'd be potentially damaging the user's icarus configuration, so not a great idea.

**Comment by quinton-ashley** [comment]
Okay I've decided not to store the board name if it is irrelevant but the version number could be important if users have different versions of the game cause the database isn't just for the game art it also stores the path to the game file.  Using the SHA256 would be easy but I'd prefer making a shorter unique id because Nostlan uses the game ids for the image folder names.

I understand the concern about editing the file but I'd like to at least be able to read the location of their Super Famicom folder from the icarus config file in case they changed it from being at `$home/Emulation/Super Famicom`.  Where is that file?

**Comment by Screwtapello** [comment]
That sounds like a pretty good reason to include the version number, and yeah - SHA256 sums are lovely for data structures but make for terrible filenames.

icarus loads its settings file [from the "user settings" path](https://github.com/byuu/higan/blob/3cd3df88f4e7173a19f21f7fe4b95c9a418befcb/icarus/icarus.cpp#L60-L62), which is [different locations on different platforms](https://github.com/byuu/higan/blob/3cd3df88f4e7173a19f21f7fe4b95c9a418befcb/nall/path.hpp#L84-L98). As a rough guide, however:

- `~/.config/icarus/settings.bml` on POSIX
- `~/Library/Application Support/icarus/settings.bml` on macOS
- `%APPDATA%\icarus\settings.bml` on Windows
