### ISSUE TITLE
Mac problem

### ISSUE THREAD

**Issue by azoreseuropa** [byuu/bsnes#3]
Compiling it and I got an error:

In file included from ../hiro/hiro.cpp:5:
In file included from ../hiro/core/core.cpp:33:
../hiro/core/color.cpp:7:8: error: cannot define or redeclare 'Color' here
      because namespace 'hiro' does not enclose namespace 'Color'
Color::Color(signed red, signed green, signed blue, signed alpha) {
~~~~~~~^
../hiro/core/color.cpp:8:12: error: use of undeclared identifier 'red'
  setColor(red, green, blue, alpha);
           ^
../hiro/core/color.cpp:8:17: error: use of undeclared identifier 'green'
  setColor(red, green, blue, alpha);
                ^
../hiro/core/color.cpp:8:24: error: use of undeclared identifier 'blue'
  setColor(red, green, blue, alpha);
                       ^
../hiro/core/color.cpp:8:30: error: use of undeclared identifier 'alpha'
  setColor(red, green, blue, alpha);
                             ^
../hiro/core/color.cpp:11:8: error: cannot define or redeclare 'operator bool'
      here because namespace 'hiro' does not enclose namespace 'Color'
Color::operator bool() const {
~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [obj/hiro-cocoa.o] Error 1

**Comment by byuu** [comment]
Thanks, I'll try to fix this one tomorrow, but the macOS port will still be very broken, as I don't have a hiro/cocoa maintainer currently =(

**Comment by byuu** [comment]
I looked into this, and I don't see an issue with the code ...

struct Color {
  Color(int red, int green, int blue, int alpha = 255);
};

Color::Color(signed red, signed green, signed blue, signed alpha) {
  setColor(red, green, blue, alpha);
}

../hiro/core/color.cpp:7:8: error: cannot define or redeclare 'Color' here
because namespace 'hiro' does not enclose namespace 'Color'

Color is not a namespace, but rather a struct. I never attempted to use Color as a namespace.

I'll need more information to diagnose this issue ...

**Comment by byuu** [comment]
Aha! LIJI gave the key insight. It's the Cocoa Viewport fix.

This is fixed now in the latest commit, sorry for the trouble!
