### ISSUE TITLE
"Missing" features?

### ISSUE THREAD

**Issue by levonnn** [byuu/bsnes#305]
I was wondering if it's intended or something overlooked.

When compared to byuu, several things are rather different in bsnes:
-Color emulation option is missing in bsnes and I can't really reproduce same colors as on byuu;
-Gamma settings are different: 100% in byuu is like 200% in bsnes;

And probably the most important: screen darkening. Final Fantasy VI on bsnes darkens screen completely during map change. Higan and byuu don't so we can see a new map scrolling. I read it's supposed to be like that on real hardware. Was that removed?

**Comment by byuu** [comment]
Since bsnes only emulates the SNES, a gamma setting of 150% approximates the color emulation option + 100% gamma. If you leave color emulation off in byuu, 100% gamma should be the same in both.

bsnes sacrifices 24-bit color that is *required* to emulate the FF6 dark screens being just barely visible (really, you need a 30-bit display but supporting that color depth is just too difficult with modern graphics drivers and desktop modes.) It does this so that it can support 16-bit software filters that can't work with 24-bit output (blargg's snes_ntssc, HQ2x's lookup tables, etc.) Since byuu doesn't support software filters, it doesn't have to force INIDISP.d0-3=0 to true black.

**Comment by levonnn** [comment]
Thanks for detailed explanation!
Oh well, I guess for purist weirdos it's either higan or byuu. Otherwise bsnes is amazing.
