### ISSUE TITLE
bsnes's ROM region detection fails with homebrew game

### ISSUE THREAD

**Issue by Ramsis-SNES** [byuu/bsnes#40]
Specifically, my own homebrew game ([latest public build](https://github.com/Ramsis-SNES/furryrpg/raw/master/furryrpg.sfc)) is mysteriously detected as an -ESP (and thus, PAL) game, while it's actually US (region code in internal header: $01).

From the manifest viewer:

```
game
  sha256:   497c90676752d0c633e222f9293cf5d3c12d175842d6c6cc65fe1eb72398e522
  label:    furryrpg
  name:     furryrpg
  title:    FURRY RPG!
  region:   SNSP-SNES-ESP
  revision: SNSP-SNES-0
  board:    EXHIROM-RAM-SHARPRTC
```
All other test hardware/software I'm using (sd2snes, higan, Snes9x) correctly recognize the ROM as US/NTSC. The only workaround I found so far is to provide a custom manifest (<romname.bml>) with the correct region information within the same folder as the ROM itself.

**Comment by byuu** [comment]
Do you have data at $ffb0? (the extended region.)
I will look into this and fix it, thanks for the report.

**Comment by Ramsis-SNES** [comment]
Thanks for the quick reply, byuu! :-) Indeed, I do have some ASCII data beginning at $(40)FFB0 (namely, "00SNES"). The $(40)FFDA byte is set to $33 like most later games did. Please do not hesitate to let me know if/how I could improve the internal header structure of my game – I did put it together to my best knowledge, which might not be 100% accurate though.

**Comment by byuu** [comment]
Yeah, that's why. 0x33 is the publisher ID indicating that $(40)ffb0 is valid.

I then further validate it by ensuring ffb0-ffb5 are all [0-9A-Z], which '00SNES' is. So that means I think the game serial is stored in ffb2-ffb5, and get "SNES" (it's usually like AxxJ, AxxS, etc.) S in this case is the region code for Spain.

https://github.com/byuu/bsnes/blob/master/bsnes/heuristics/super-famicom.cpp#L406

Suggestions: don't use $33 for the publisher code, or format $ffb0 data to its actual values ($ffb5 is supposed to be the region code letter that you'd find at the bottom right of cartridge labels.)

Cheers ^-^

**Comment by Ramsis-SNES** [comment]
Aha, that clears things up. ^^ Thank you, I'll reformat the header in some other way. Also, I just looked into why higan boots the game in 60 Hz and well, looks like I have a manifest in the game folder that declares the ROM to be US/NTSC ... D'oh! Silly maned me! XD Thanks again!
