### ISSUE TITLE
Graphics glitches in Mighty Morphin Power Rangers - The Fighting Edition

### ISSUE THREAD

**Issue by underwaterworldjungle** [byuu/bsnes#41]
Mighty Morphin Power Rangers - The Fighting Edition (USA and Europe versions).
In bsnes v108 (not in v107 and higan), during the ingame fights, bar-shaped glitches appear in the Megazord sprites, also the bar/time display elements repeat and scroll at the top of screen.
Appears the same as here: https://www.romhacking.net/forum/index.php?topic=25789.msg352346#msg352346
Thank you.

**Comment by Max833** [comment]
I tested this, too. More information, @byuu :

- bsnes 108.5
- verified usa rom
- start the game -> story mode -> first fight
- glitches appear with and without "accuracy mode"

![11](https://user-images.githubusercontent.com/53529402/62478567-b5450200-b7ab-11e9-8fc8-eecd81a2268a.png)
![22](https://user-images.githubusercontent.com/53529402/62478578-b9711f80-b7ab-11e9-9e53-f5d9f4834102.png)

**Comment by byuu** [comment]
It would be nice if the person on RHDN mentioned what the issue was when fixing things ^^;
I'll take a look, thanks.

**Comment by byuu** [comment]
Fixed in v108.6, thanks for the report!

**Comment by byuu** [comment]
Oh, for @SourMesen: see https://github.com/byuu/bsnes/commit/57579490231028b8156192316c047b581cb66d72#diff-14abf056212c4196458e4a664c583367

This is one of those stupidly sensitive IRQ games that need the IRQ lock behavior perfectly correct. I was trying to speed things up and only clear the IRQ lock once per cycle instead of per clock tick (so once instead of twice on CPU bus reads), but I put the irqLock clear at the start of the CPU read function instead of right before the actual read (remember the behavior I explained with reads "effectively" taking place at clocks-4 rather than at 0 or at at clocks.)

**Comment by SourMesen** [comment]
@byuu  Thanks for the info - I figured it was something to do with the irq lock logic since that was also the case the last time I fixed this game a few weeks ago. I tried tweaking stuff a bit to match as best as I could, but only managed to make it worse for the most part.

Might just have to wait until I review the entire irq/nmi logic and try to pass your nmi/irq tests before I spend more time on this one.

@Max833  Thanks for letting me know the bug was present in Mesen-S!
