### ISSUE TITLE
The Great Battle IV graphics missing

### ISSUE THREAD

**Issue by Pat86** [byuu/bsnes#54]
When you start the game / first level, all level graphics are missing, except the player and enemy characters. bsnes 108. Fast PPU on. All graphics are there with Fast PPU off.

![2019-08-18 00_11_45-freenet E-Mail Login](https://user-images.githubusercontent.com/20128108/63217802-0c07ef80-c14d-11e9-8c5c-1f329b646ee6.png)

**Comment by Max833** [comment]
Something else I noticed (Fast PPU off): When you play the first level on the upper right corner there is some flickering going on and it's not there with snes9x. Does this happen on hardware too?

bsnes: https://streamable.com/wju0t
snes9x: https://streamable.com/xh93a

**Comment by Screwtapello** [comment]
@Max833 That's pretty normal for dot-based PPUs like higan and Mesen-S. Notice that the background behind the status bar behaves one way, and the background above and below it behaves differently (for example, the background behind the status bar is black when everything else is white).

To make that effect happen, the game updates the configuration of the PPU at the end of the last scanline before the status bar, and again at the end of the last scanline *of* the status bar. If it manages to make the change in the tiny window between the end of one scanline and the beginning of the next (the "hblank" period) everything works as intended. However, if it jumps the gun and updates the PPU a bit early, the change may affect the last few pixels of that last scanline, which is what you see here.

Snes9x, the bsnes Fast PPU, and other scanline-based emulators don't have this glitch because they work differently. They emulate up to a point about half-way along the scanline without rendering any pixels, then render the entire scanline with whatever configuration the PPU had at that point, then resume emulating to the end of the scanline. That means they never get this kind of rendering glitch at the start or end of a scanline, but it also means they can't render any changes the game deliberately makes during a scanline, like the infamous Air Strike Patrol shadow.

**Comment by Max833** [comment]
Ah, I see. Interesting. Thanks for your explanation Screwtapello. :)

**Comment by byuu** [comment]
Fixed, thank you.
