### ISSUE TITLE
General information about accurate PPU

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#55]
**Graphics glitches in Unholy Night (USA) ingame [bsnes v108.11][fast PPU off]:**

![unholdy night](https://user-images.githubusercontent.com/53529402/63390361-1aeddc80-c3af-11e9-9659-d0985e2b31db.jpg)

**The Great Battle IV:**
https://github.com/byuu/bsnes/issues/54#issuecomment-522311051

**Air Cavalry (USA) (with fast PPU on and fast PPU off):**

Flickering at the top (menu selection): https://streamable.com/0oajk

Fade to Black screen is black in snes9x and Mesen-S but not with fast PPU on/off: (wait at menu until the game starts):

SNES9X: https://streamable.com/t7yk1

BSNES: https://streamable.com/p42hx

![aaaaaa](https://user-images.githubusercontent.com/53529402/63513122-a8cbe380-c4e5-11e9-8b49-06a33fc63e12.jpg)

**Comment by byuu** [comment]
I definitely appreciate this bug report, but for the accurate PPU, I cannot get pixel perfect timings due to lack of logic analyzer traces and decapped analysis of latching behaviors for internal registers. In this specific case, that could very well be there on real hardware as well, so we should confirm it for posterity. But, at the moment, I don't have the resources / time to handle issues that affect less than one scanline, I'm afraid. Still, thanks for the report, I will add it to a list and keep it in mind for the future.

**Comment by byuu** [comment]
Great Battle IV is fixed, Unholy Night is out of scope. Air Cavalry is a legitimate bug, I'm going to split to a new bug report.

**Comment by orbea** [comment]
> Unholy Night is out of scope

I am just curious about the reason for this? It is a commercial snes game that runs on real hardware or am I missing something?

**Comment by Screwtapello** [comment]
The titlebar on @Max833's screenshot says "(Unl)", so I'm guessing it's an unlicensed game. In addition, any glitch that appears for a fraction of a scanline with Fast PPU off is almost certainly how the game behaves on the original hardware.

**Comment by orbea** [comment]
>  so I'm guessing it's an unlicensed game.

Its an aftermarket snes game.

https://www.amazon.com/Retroism-Unholy-Night-Darkness-Compatible-nintendo/dp/B06Y3RB65T

> any glitch that appears for a fraction of a scanline with Fast PPU off is almost certainly how the game behaves on the original hardware.

That seems like a good reason, I wonder if anyone could confirm if this is true or not?
