### ISSUE TITLE
Addams Family, The - Pugsley's Scavenger Hunt (USA) [bsnes v108.11][Fast PPU on]

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#58]
https://streamable.com/hzhz6

Works fine with fast PPU off and snes9x.

Edit: Same problem at the bottom (sometimes at the top too) with "Adventures of Kid Kleets, The (USA) (En,Fr,Es)", "Adventures of the Rocketeer, The (Japan)", "Aerobiz (USA)", "Aguri Suzuki F-1 Super Driving (Europe)", "AIII S.V. - A Ressha de Ikou 3 - Super Version (Japan)" "Al Unser Jr.'s Road to the Top (USA)" "Albert Odyssey (Japan)" "Albert Odyssey 2 - Jashin no Taidou (Japan)" "Another World (Europe)" "Aqutallion (Japan)" "Ardy Lightfoot (Europe)" "Arkanoid - Doh It Again (Japan) (En)" "Asameshimae Nyanko (Japan)" "Ashita no Joe" and more

**Comment by byuu** [comment]
![Screenshot_2019-08-24_08-48-00](https://user-images.githubusercontent.com/2107894/63601502-81b60480-c600-11e9-910e-3a7ef487f903.png)

Doesn't happen to me ...

**Comment by byuu** [comment]
Sometimes this is to be expected though. The SNES offsets the scanlines by 1 for sprites and if games don't compensate, the final line is sometimes rendered wrong. I guess I can add a 'mask final scanline' option.

**Comment by Max833** [comment]
OK, thanks byuu. Really weird. No matter how often I start those games, the last scanline is always there.

**Comment by byuu** [comment]
Even in the latest WIP right now? Hmm ... I can't imagine what'd cause it to only happen on Windows.

**Comment by Max833** [comment]
This is the latest version, right? https://github.com/byuu/bsnes/commit/db1c37c799c63e5ee8123831120e5a23746f1c9f The last scanline and this https://github.com/byuu/bsnes/issues/60 is still like before, yes.

**Comment by byuu** [comment]
Yeah well, sorry then, I tried almost every game in your list and it's just not happening here, so I'm not going to be able to fix this one for you ...

**Comment by Max833** [comment]
I deleted %AppData%/Roaming/bsnes/settings.bml and now everything is fine! I changed some settings again, but I can't reproduce this issue. I have no idea what caused this. The only thing I noticed is that you can see with the rewind feature, that this scanline changes color. But yeah, not really a problem. ^^

Thanks byuu. You're awesome. :-)

**Comment by byuu** [comment]
Skew is a holdout for static rate control ... there's really not a reason to have it, so I'll remove it. It had too many values for a slider which is why it was hard to get it back to 0 (have to use the keyboard.)

The final scanline being wrong is a thing in several SNES games. It has to do with the screen height showing one scanline of a new tile row at the bottom. Lots of developers ignored it because it's cut off by the TV overscan area area, but not on LCDs with emulators.

#54 comment: that's a raster effect. The game is writing to the display registers too late. You see this *a lot* in NES games without HDMA, and sometimes in dumb SNES games that didn't know about HDMA and used IRQs.

Okay well if you can reproduce the scanline issue let me know, but for now we'll mark it as corrected. Very weird. I do believe it was happening to you, I just can't fix things I can't reproduce ^^;
