### ISSUE TITLE
Battle Grand Prix (Japan) (En) - blackscreen

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#64]
When I press start the game freezes(?) **sometimes** and all I can see is a black screen. Works **always** with SNES9x but not with bsnes or Mesen-S, @SourMesen

**Comment by byuu** [comment]
I'll take a look. If I figure out what's wrong I'll relay to Sour. It's almost certainly IRQ related.

**Comment by byuu** [comment]
Does this happen with higan v106 by the way?

**Comment by Max833** [comment]
The game starts every time with higan v106. So... it's like Snes9x 1.60.

**Comment by byuu** [comment]
Here's the fix:
https://github.com/byuu/bsnes/commit/ce3dba130c60f611e785d2497cff073b0f3afc80

Basically this game is absolute pure evil and requires 100% perfect CPU<>DMA sync, which I messed up very slightly in v106.62 trying to simplify the number of operations needed for DMA transfer cycle counting.

The reason it works in Snes9X is because if your timing is off by a lot, it works. It only starts breaking when you near perfection.
