### ISSUE TITLE
Beavis and Butt-Head (Europe) - purple scanline(?) at the top

### ISSUE THREAD

**Issue by Max833** [byuu/bsnes#71]
SD2SNES Pro has arrived! =)

bsnes: https://streamable.com/d2lhi (00:01 and 00:08)

Hardware: https://streamable.com/u01r7 (01:25 and 02:00)

**Comment by byuu** [comment]
It's a pretty good example of our mosaic emulation not being 100% correct. Mosaic is very tricky to get right. I'll see if I can fix this without breaking all the difficult mosaic edge cases like Super Turrican and that one Sim (something) game.

**Comment by byuu** [comment]
![Screenshot_2019-08-31_06-37-29](https://user-images.githubusercontent.com/2107894/64052535-d8e84600-cbb9-11e9-90c9-898924821f6d.png)

The purple part is fixed. There's still one frame like this, which is caused by the game disabling the screen a few scanlines into the frame, so that's supposed to be there.
