### ISSUE TITLE
[Super Game Boy] MLT_REQ (Killer Instinct, Pokemon Yellow)

### ISSUE THREAD

**Issue by byuu** [byuu/bsnes#77]
https://github.com/byuu/bsnes/commit/03aaaba889c78dab6a1c17239108864c8c469ee3

Pokemon Yellow requires MLT_REQ set to 3. Not setting it, or setting it to anything other 3, prevents the game from detecting the Super Game Boy.

https://github.com/byuu/bsnes/issues/74

Killer Instinct requires MLT_REQ set to 0. It may (or may not, I didn't test) allow 1 or 2, but it will not allow 3. If set to 3, the game defaults to player 2 instead of player 1.

https://github.com/byuu/bsnes/issues/53

As they require conflicting values, I don't know how to fix this for both games simultaneously. For now, Killer Instinct is the one to get penalized, and will default to player 2, as it's the less severe issue.

**Comment by endrift** [comment]
Related to https://github.com/mgba-emu/mgba/issues/1104.

**Comment by endrift** [comment]
Here's my fix for this, which may or may not be correct but I can't confirm without a working SGB: https://github.com/mgba-emu/mgba/commit/74e09675ce2792d6a4fc79c9f4fe1f893513efac

**Comment by byuu** [comment]
Doesn't work for me, unfortunately. I set JOYP_ID to 3 on reset already, and just masking JOYP_ID but not resetting it to zero causes Pokemon Yellow's SGB functionality to stop working again. I guess the bug between our emulators is different after all, sigh =(

**Comment by endrift** [comment]
I have confirmed my fix is not correct. The initial value is in fact 0.

Also regarding Pokemon Yellow detection:
Detection works in two phases: it tries to read the value after sending the MLT_REQ, and if that's still & 3, it does some load/store modification and tries again. There's a bug where it doesn't disable interrupts in between the checks so the vblank IRQ fires multiple times, leading to JOYP being read a bunch. However, in BGB and SameBoy it never falls through the first check so that bug doesn't matter. On HARDWARE it DOES fall through that first check. I tried breaking just the first and just the second in two different ROMs. The first still detects. The second does not. Thus the second check is both reached and passes on hardware.

**Comment by endrift** [comment]
Okay I figured it out, it's not about initialization, it's about incrementing. It always initializes to 0, but incrementing works by writing 0x10 _toggling_ whether or not the next 0x30 advances the controller:

0x10 0x30: **Increment**
0x20 0x30: No increment
0x10 0x20 0x30: Increment
0x20 0x10 0x30: Increment
0x10 0x20 0x10 0x30: **No increment**

This behavior has been verified on hardware using [this test ROM](https://cdn.discordapp.com/attachments/327738013239083010/618303537910251521/mlt_req_1.gb) ([source](https://cdn.discordapp.com/attachments/327738013239083010/618303503793782784/mlt_req_1.s))

**Comment by byuu** [comment]
Fixed for the test ROM, Pokemon Yellow, and Killer Instinct in both higan-gb and bsnes-SameBoy. Thanks endrift! ^-^
