### ISSUE TITLE
PAL to NTSC patches ignored

### ISSUE THREAD

**Issue by bajolzas** [byuu/bsnes#78]
Im playing Terranigma, a game that was only released in english in europe, and therefore runs slower at 50hz.
Im also using this patch https://www.romhacking.net/hacks/541/ to convert it to 60hz and it works on snes9x.

However bsnes still runs it at 50hz, with or without the patch applied.
Even tried the original 60hz japanese version and it runs faster that the european version on bsnes.

Im guessing this happens with any other region converted game.

**Comment by byuu** [comment]
It's not being ignored, the patch isn't changing the region from PAL to NTSC.
And even when I force the emulator to run in 60hz mode, it errors out because it's still trying to run in PAL mode.

Don't ask me why it works on Snes9X, I have no idea.

![Screenshot_2019-09-03_11-22-56](https://user-images.githubusercontent.com/2107894/64139957-bbc3a980-ce3d-11e9-9c52-b8c10053834f.png)

![Screenshot_2019-09-03_11-24-38](https://user-images.githubusercontent.com/2107894/64139959-be260380-ce3d-11e9-846c-2455e27a91e4.png)

![Screenshot_2019-09-03_11-25-02](https://user-images.githubusercontent.com/2107894/64139960-bfefc700-ce3d-11e9-8123-4d51edeb4615.png)

![Screenshot_2019-09-03_11-25-16](https://user-images.githubusercontent.com/2107894/64139966-c2522100-ce3d-11e9-80ce-148bb2fb09a6.png)

**Comment by byuu** [comment]
Oh, this is why:

"This is a patch to convert the PAL version of Terranigma to NTSC.  It removes
the PAL protections, sets the region to USA, and renames the internal name to
"TERRANIGMA USA" as is Enix's designation for a game released in USA.

To install, apply this IPS file to your Terranigma ROM image, which should be 4,194,816 bytes in length.  If your ROM image is 4,194,304 bytes in length, you need to use SNESTOOL to add a header.

If you have any problems, please contact me at BFeely@aol.com"

It expects a headered image. This is what happens when people use trashfire formats like IPS.

**Comment by byuu** [comment]
![Screenshot_2019-09-03_11-42-25](https://user-images.githubusercontent.com/2107894/64140624-05ad8f00-ce40-11e9-8350-ea305a473f98.png)

Okay, this will be in the next WIP. Hit "Yes" when loading the game and it'll work. Snes9X is just defaulting to assuming there is a header, even though your ROM doesn't have one.

**Comment by bajolzas** [comment]
I did use a headered rom as expected though. 
Cant check if it fixes it as I'm not at home right now, but that fix does not seem to be targeting the problem :/
