### ISSUE TITLE
Scanlines are uneven at 4K in full-screen in the “Center” mode with blur disabled

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#85]
Some scanlines (each 7th at 4K) are thicker than other ones at the 4K (3840×2160) resolution in the “Center” mode with blur disabled. Image line directly above each thicker scanline is narrower than other image lines. Does not depend on scanlines’ transparency (0%, 33%, 66%).

This could be expected in the “Scale” mode due to natural Nearest-Neighbour distortions at _fractional_ ratios, but the “Center” mode specifically uses _integer_ ratios.

Note that the issue does _not_ reproduce at Full HD (1920×1080), but does at 4K (3840×2160). It also does not reproduce with blur enabled, you should _disable blur_ to see it (Settings  → Shader → None).

Below is a comparison of screenshots of bsnes 108.17 nightly in full-screen mode with 9x size (scanlines are uneven) and in windowed mode with 8x size (maximum available size in windowed mode) (scanlines are uniform).

![Screenshot](https://user-images.githubusercontent.com/1833563/64391612-0d448200-d052-11e9-9577-933db90cfb1e.png)

**Comment by byuu** [comment]
I can't fix this.

**Comment by Marat-Tanalin** [comment]
> you just can't insert scanlines into a non-even multiplier in a way that will look like actual scanlines and not just a screen door effect.

Not sure what you mean.

**Comment by Screwtapello** [comment]
In progressive scan mode, the SNES outputs ~240 lines per frame. At 9× scale, each horizontal line of SNES pixels is draw with 9 horizontal lines of display pixels, for a total of 2,160 lines of display pixels, exactly the height of a 4K monitor.

If you turn on the "scanline" filter, each line of SNES pixels is drawn with a darker copy of that line below it, for a total of 480 lines per frame. At 9× scale, that's 4,320 lines of display pixels, or Way Too Many Lines. Instead, for consistency with unfiltered mode, the image with scanlines is actually drawn at 4.5× scale, which takes us back to 2,160 lines of display pixels again. Unfortunately, even though "Center" mode tries to use integer ratios, in this situation it's forced to use a non-integer ratio of 4.5, so this kind of uneven lumpiness is inevitable.

The windowed mode 8× scale is fine, because instead of drawing a 240-line frame at 8×, it's drawing a 480-line frame at 4×. 1080p fullscreen is also fine, because the largest integer multiple it can display is 4×, which is really 2× with scanlines or interlaced mode.

If you want the smoothest possible scanlines at an arbitrary output resolution, use the Pixellate shader or something like it to anti-aliase those rounding errors and hide them as much as possible.

**Comment by Marat-Tanalin** [comment]
In the most trivial case, an even ratio would indeed be always used if scanlines are enabled. Such approach is apparently used in Snes9x.

A more advanced implementation could use different scanline-width/image-line-width ratio depending on whether the scaling ratio is even or odd:

    scanlineWidth  = floor(ratio / 2);
    imagelineWidth = ratio - scanlineWidth;

So e.g. for 4K with its integer ratio of 9, scanline width would be 4: `floor(9 / 2)`, and image line would be 5: `9 - 4`.

This algorithm is simple, universal and does not need to be reimplemented separately for each single scaling ratio.

**Comment by Screwtapello** [comment]
Yes, instead of the scanline filter being hard-coded to 2× scale, it could render a complete 9× output frame and have complete control over where the rounding occurs.

Unfortunately, even on a modern multi-core super-fast CPU, rendering anything over 720p in pure software, even something as simple as a scanline effect, is cripplingly slow. Any full-screen graphical effect needs to be done on the GPU as a shader to have any chance of running at a reasonable speed.

I don't actually know of a shader that renders something like the scanline-filter effect. There's the [Gaussian Scanlines](https://github.com/hizzlekizzle/quark-shaders/tree/master/Gaussian%20Scanlines.shader) shader, but it's a lot more realistic and detailed than the old scanline filter. Honestly, I still think you'll achieve the best possible result by using the scanline filter with the pixellate shader to handle rounding errors.

**Comment by Marat-Tanalin** [comment]
> even on a modern multi-core super-fast CPU, rendering anything over 720p in pure software, even something as simple as a scanline effect, is cripplingly slow.

Potential performance impact is a potentially good point. Did you do benchmarking specifically regarding properly-even scanlines or something alike? What exact frame rate would it result in on a 4K display?

According to **Ant_222** who implemented a DOSBox [patch](https://www.vogons.org/viewtopic.php?t=49160) for pixel-perfect (integer-ratio) scaling (available in [DOSBox ECE](https://dosboxece.yesterplay.net/en/)), pure-software scaling implementation provides performance of about 557 scaled megapixels per second on the quite old (August 2011) AMD A4-3400 CPU which gives about 90&nbsp;fps for 4:3 image on a 4K display. I suspect adding scanlines (at least 100% opaque so that no color-mixing calculations needed, just pure-black lines) should not add a serious extra performance impact.

> you'll achieve the best possible result by using the scanline filter with the pixellate shader to handle rounding errors.

I see just two options in the “Shader” submenu of bsnes v109: “None” and “Blur”.

Fwiw, I’m interested in true pixel-perfect [integer-ratio](http://tanalin.com/en/articles/lossless-scaling/) upscaling, not just an image looking pixelated.

**Comment by Marat-Tanalin** [comment]
## GPU-accelerated uniform scanlines as an image layer

@Screwtapello

> Any full-screen graphical effect needs to be done on the GPU

A hardware-accelerated way to implement uniform scanlines is using scanlines as an **image layer with tunable opacity**.

By nature, adding scanlines doesn’t process the original image itself in any way, so scanlines don’t have to be rendered at each frame, they can be (pre)rendered **once**.

The scanlines’ image could be generated on the fly once the scanlines mode is enabled via emulator settings (this should be fast-enough to be unnoticeable), or a fixed number (for resolutions up to 8K) of prerendered embedded images could be used.

The scanlines’ images could be 1-pixel-wide and then stretched via GPU to the needed width.

Both layering and stretching can be hardware-accelerated with GPU.

**Comment by Marat-Tanalin** [comment]
Fwiw, added scanlines’ support to my [live web demo](http://tanalin.com/_experimentz/demos/non-blurry-scaling/) of nonblurry integer-ratio scaling.

Scanlines width is calculated as `floor(ratio / 2)` as described in [one](#issuecomment-528845057) of my previous comments, so scanlines are uniform _regardless_ of whether scaling ratio is even or odd.

**Comment by MT-ru** [comment]
Looks like the issue is specific to **OpenGL 3.2** video backend (“driver” in terms of bsnes) and does not reproduce with other backends such as Direct3D 9.0, DirectDraw 7.0 and GDI.

So it’s apparently not even a general issue with scanlines, it’s a rendering _inconsistency_ between different rendering backends.

Using a non-OpenGL backend is fine, but DirectX and GDI are Windows-only, so macOS and Linux users might not have options other than OpenGL and might therefore be affected by this issue to a greater extent than Windows users.

(There is apparently an odd temporary issue with commenting from my main account.)
