### ISSUE TITLE
Settings → Output → “Blur emulation” does nothing

### ISSUE THREAD

**Issue by Marat-Tanalin** [byuu/bsnes#86]
Looks like the option “Settings” → “Output” → “Blur emulation” does nothing. Actual blur can be enabled with “Settings” → “Shader” → “Blur”.

**Comment by byuu** [comment]
It affects pseudo-hires games. The two most prominent are Kirby's Dream Land 3 and Jurassic Park. It won't do anything in most games. I'll think of a way to rename the option to be more clear though.

![pseudo-hires](https://user-images.githubusercontent.com/2107894/64394816-e195bc00-d092-11e9-94fb-ad48303fe721.png)

**Comment by Marat-Tanalin** [comment]
So is it about _blending_ layers instead of blur?

**Comment by Screwtapello** [comment]
No.

The SNES graphics hardware supports "blending" different background layers together to produce a transparent effect. as seen in [the battle menus of Star Ocean](https://en.wikipedia.org/wiki/Star_Ocean_(video_game)#/media/File:Star_ocean_super_famicom_battle.jpg). This behaviour is not blending.

A typical standard-definition CRT television can draw ~340 vertical "lines" across the screen from left to right. That means the standard 256-pixel SNES resolution can display each pixel fairly clearly. However, that's not enough for the 512-pixel display mode; in practice, it's a *little* bit sharper than the 256-pixel mode, but the individual pixels the SNES puts out are mostly blurred together, resulting in a transparency-like effect.

Kirby and Jurassic Park are using this high-res 512-pixel mode, expecting that adjacent pixels will be blurred together, to create a transparency-like effect. Other games use the high-res 512-pixel mode to render sharper, more legible text, so blurring together adjacent pixels kind of ruins the effect (or at least makes it look very anti-aliased). That's why it's an option.

**Comment by Marat-Tanalin** [comment]
Thanks for the great explanation. So it’s still about blending (or mixing), but not layers, but columns.

Then a possible more clear name for the option is “Mix adjacent columns at double resolution”.

**Comment by Marat-Tanalin** [comment]
> I'll think of a way to rename the option to be more clear though.

Is there another issue where you are planning to track such renaming?

**Comment by Marat-Tanalin** [comment]
Looks like in Snex9x, a similar option is named **“Blend Hi-Res Images”** (Video → Display Configuration → SNES Image).
