### ISSUE TITLE
v109 Windows binary uses AVX instructions

### ISSUE THREAD

**Issue by cremno** [byuu/bsnes#88]
>Unhandled exception at 0x00000000005E73F0 in bsnes.exe: 0xC000001D: Illegal Instruction.

>00000000005E73F0  vmovups     xmm0,xmmword ptr [rbx+rax]  

Likely just a mistake - `local=true`?

**Comment by byuu** [comment]
Ah, that could be it. Okay give me a few minutes then.

**Comment by byuu** [comment]
Alright done, please reopen if it doesn't work still.

**Comment by Marat-Tanalin** [comment]
Do I understand correctly that there are now _two_ different v109 variants?

**Comment by Screwtapello** [comment]
There is one definitive version of v109's source-code, but different people can build it in different ways, producing different binaries.

Most people building bsnes from source are building it for themselves on their own computer, so the default configuration is "use all the fancy tricks my CPU can handle". However, if you're building a bsnes binary to distribute to other people (like the Cirrus CI nightly builds, or byuu's official binaries, or a Linux distro or something) you'll want to turn it down a bit.

The originally-uploaded bsnes binaries were tuned for byuu's high-end development workstation, and consequently didn't work for a lot of people. The currently-available binaries are built from the same source, but with less aggressive tuning.

**Comment by Marat-Tanalin** [comment]
For end user consuming prebuilt binaries, those are effectively different versions even if source code is the same.

Such inconsistencies are typically resolved by either bumping version number or providing a build number besides a version number, to prevent confusion.

> — What bsnes version are you using?
> — v109
> — What version of v109?
> — o_O

**Comment by Screwtapello** [comment]
If you look at [the list of tags in the repository](https://github.com/byuu/bsnes/tags), you'll see a number of tags with a "b" suffix. Those are generally case where byuu made a release, somebody reported a problem, and he quickly patched the code and and released new, fixed versions with the same version number. I couldn't quite bring myself to force-move the tag to another commit, though, so I just made a new tag with a "b" (I don't think we ever got as far as "c").

I understand where you're coming from, but if byuu's happy to field support questions caused by different builds having the same version number, I'm happy to let him. It's his project, after all.
