### ISSUE TITLE
"-march=native" parameter causes bsnes failed to launch on some CPU

### ISSUE THREAD

**Issue by owomomo** [byuu/bsnes#97]
GNUMakefile in bsnes 109 changed `-march=native` to a global parameter, but it will make Windows build fail to run on some clients. I think it's because their CPU architechture is different from mine, and only the instructions from the CPU of my own machine are included to the binary. When I changed to `local := false` such promblems are solved. However, I don't know why the one downloaded in the official site can run on all the Windows. If it is compiled with the same code released on the public, then why the problem doesn't occur?
I use msys2 with 64 bit mingw, the only possible reason I can think is the official bsnes is compiled with another compiler which has a different default arch configuration, or a mindblowing inferring is the machine is old enough for most modern CPUs compatible its instructions.
I suggest to set `local` variable in GNUMakefile to false in the public code to prevent problems like this.

**Comment by Screwtapello** [comment]
Anyone that builds binaries for redistribution (like the automated nightly builds, byuu's official binaries, Linux distros, etc.) should use `local=false`. You don't have to edit `GNUMakefile`, because it's a variable you can set it on the command-line:

    make target=bsnes local=false -j5

(or whatever)

The vast majority of people building bsnes are building it for their own personal use, so `local=true` is the default.

**Comment by byuu** [comment]
Yeah this is working as intended, even if I forgot myself for a minute when posting the v109 binaries.
