### ISSUE TITLE
Game Paks not working

### ISSUE THREAD

**Issue by Anuskuss** [byuu/bsnes#99]
###### This is my folder layout:
```
Nintendo PowerFest '94 (USA).sfc/
├─ dsp1.data.rom
├─ dsp1.program.rom
├─ manifest.bml
├─ Nintendo PowerFest '94 (USA).sfc
├─ Nintendo PowerFest '94 ~ Ken Griffey Jr. Presents Major League Baseball (USA).sfc
├─ Nintendo PowerFest '94 ~ Super Mario Bros. - The Lost Levels (USA).sfc
└─ Nintendo PowerFest '94 ~ Super Mario Kart (USA).sfc
```

###### This is my manifest:
```bml
board region=ntsc
	event=PF94 timer=360
		map address=10,20:6000
		map=mcu address=00-3f,80-bf:8000-ffff
		map=mcu address=c0-ff:0000-ffff
		rom name="Nintendo PowerFest '94 (USA).sfc" size=0x40000
		rom name="Nintendo PowerFest '94 ~ Super Mario Bros. - The Lost Levels (USA).sfc" size=0x80000
		rom name="Nintendo PowerFest '94 ~ Super Mario Kart (USA).sfc" size=0x80000
		rom name="Nintendo PowerFest '94 ~ Ken Griffey Jr. Presents Major League Baseball (USA).sfc" size=0x100000
		ram name=save.ram size=0x2000 volatile
			map address=30-3f,b0-bf:6000-7fff mask=0xe000
	necdsp model=uPD7725 frequency=8000000
		map address=00-0f,80-8f:6000-7fff mask=0xfff
		prom name=dsp1.program.rom size=0x1800
		drom name=dsp1.data.rom size=0x800
		dram name=dsp1.data.ram size=0x200 volatile

information
	title:  Nintendo PowerFest '94
	region: NTSC
	sha256: d7cf278767973c8aa66681dde46b5f6c61d4bbb0356b8b97d53b43cac750bf9f
```

This works perfectly fine in higan, but does nothing in bsnes.

###### More ideas:
- I'd like to have more popups like `Bad ROM` or `Malformed Manifest` (IIRC there is one popup about missing firmware) instead of just nothing; would be a lot more useful in finding the error.
- Support for zipped Game Paks, where the SRAM gets either rezipped with the other files or placed in the `Saves` folder.
- A wiki with information about the manifest format since there seems to be multiple revisions ([this](https://www.reddit.com/r/gamecollecting/comments/19acmy/nintendo_powerfest_94_roms_publicly_released_1000/c8mdbmd/) is very different to mine)

###### Not related to this (suggestions from Reddit):
- Device agnostic input system / SDL
- Fullscreen toggle in *Settings* -> *Output*
- Sleep thread while idling (quieter CPU fans)

**Comment by Screwtapello** [comment]
Thanks for reporting this issue with PF '94! Just to address some of your other comments:

- The manifest format isn't really documented because byuu still hasn't settled on exactly what it should look like.
- bsnes does support SDL on Linux at least. It's not useful on Windows because the "WIndows" input driver already supports everything (RawInput for keyboard/mouse, XInput and DirectInput for gamepads)
- The problem with putting a fullscreen toggle in the menus is that the menus aren't accessible from fullscreen mode, so you couldn't leave fullscreen mode again. Anyone who figures out how to enter fullscreen mode via the hotkey automatically knows how to leave it again.
- When you sleep a thread, you have very little control over when it wakes up. In order to keep audio lag at a minimum, bsnes can't sleep for very long, and busy-waiting guarantees it won't over-sleep.

I'll leave this issue open for the PF'94 thing, but if you want to talk about those other issues, please file other issues for them so they can be discussed individually.

**Comment by byuu** [comment]
Gamepaks work fine. I don't support CC'92 or PF'94, they're too much work and nobody will ever agree on how to distribute them. There's not even a clean dump of CC'92.
